[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "customer-behavior-prediction"
version = "0.1.0"
description = "Customer behavior prediction platform"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "matplotlib>=3.11.0",
    "numpy>=2.4.0,<2.5.0",
    "pandas>=3.0.3",
    "seaborn>=0.13.2",
    "ipykernel>=6.29.5",
    "scikit-learn>=1.6.0",
    "joblib>=1.4.2",
    "tensorflow>=2.21.0",
    "shap>=0.52.0",
    "lime>=0.2.0.1",
]

[tool.setuptools.packages.find]
where = ["."]
include = ["src*"]
namespaces = true

[tool.uv.workspace]
members = [
    "ipykernel",
]
